[config]

[templates.sharkshell-kitty]
input_path = "@TEMPLATE_DIR@/kitty.conf"
output_path = "/home/matko/.config/sharkshell/kitty/kitty-dynamic.conf"

[templates.sharkshell-niri]
input_path = "@TEMPLATE_DIR@/niri-borders.kdl"
output_path = "/home/matko/.config/sharkshell/niri/borders.kdl"
