pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import "Util.js" as Util

Singleton {
  id: root

  readonly property string homeDir: Quickshell.env("HOME")
  readonly property string genDir: homeDir + "/.config/sharkshell"
  readonly property string kdeColorsPath: root.genDir + "/kde-dynamic.colors"
  readonly property string qtengineConfigPath: homeDir + "/.config/qtengine/config.json"
  readonly property string gtk3CssPath: homeDir + "/.config/gtk-3.0/gtk.css"
  readonly property string gtk4CssPath: homeDir + "/.config/gtk-4.0/gtk.css"
  readonly property string gtk3IniPath: homeDir + "/.config/gtk-3.0/settings.ini"
  readonly property string gtk4IniPath: homeDir + "/.config/gtk-4.0/settings.ini"
  readonly property string flatpakOverridesPath: homeDir + "/.local/share/flatpak/overrides/global"

  property string iniText3: ""
  property string iniText4: ""

  function iconTheme(dark) {
    var d = (dark === undefined ? DynamicTheme.darkMode : !!dark)
    return d ? "Papirus-Dark" : "Papirus"
  }

  function hexToRgb(hex) {
    var m = /^#?([0-9a-fA-F]{6})([0-9a-fA-F]{2})?$/.exec(String(hex || ""))
    if (!m)
      return "0,0,0"
    return parseInt(m[1].substr(0, 2), 16) + "," + parseInt(m[1].substr(2, 2), 16) + "," + parseInt(m[1].substr(4, 2), 16)
  }

  function roleRgb(name, fallback) {
    return root.hexToRgb(DynamicTheme.role(name, fallback))
  }

  function kdeColorsText() {
    var bg = root.roleRgb("background", "#111111")
    var surf = root.roleRgb("surface", "#111111")
    var contLow = root.roleRgb("surface_container_low", "#111111")
    var cont = root.roleRgb("surface_container", "#111111")
    var contHigh = root.roleRgb("surface_container_high", "#111111")
    var contHighest = root.roleRgb("surface_container_highest", "#111111")
    var onSurf = root.roleRgb("on_surface", "#ffffff")
    var onSurfVar = root.roleRgb("on_surface_variant", "#888888")
    var onBg = root.roleRgb("on_background", "#ffffff")
    var prim = root.roleRgb("primary", "#bbbbbb")
    var onPrim = root.roleRgb("on_primary", "#000000")
    var primCont = root.roleRgb("primary_container", "#bbbbbb")
    var onPrimCont = root.roleRgb("on_primary_container", "#000000")
    var ter = root.roleRgb("tertiary", "#888888")
    var err = root.roleRgb("error", "#ff5555")
    var onErr = root.roleRgb("on_error", "#000000")
    var invSurf = root.roleRgb("inverse_surface", "#ffffff")
    var invOnSurf = root.roleRgb("inverse_on_surface", "#000000")
    function sec(n, v) {
      var L = ["[" + n + "]"]
      var keys = ["BackgroundAlternate", "BackgroundNormal", "DecorationFocus", "DecorationHover", "ForegroundActive", "ForegroundInactive", "ForegroundLink", "ForegroundNegative", "ForegroundNeutral", "ForegroundNormal", "ForegroundPositive"]
      for (var i = 0; i < keys.length; i++)
        L.push(keys[i] + "=" + v[i])
      return L.join("\n")
    }
    var L = []
    L.push("# Generated by sharkshell app theme - do not edit.")
    L.push("[General]")
    L.push("ColorScheme=SharkDynamic")
    L.push("Name=SharkDynamic")
    L.push("shadeSortColumn=true")
    L.push("")
    L.push(sec("Colors:Window", [contLow, bg, prim, prim, prim, onSurfVar, prim, err, onSurf, onBg, ter]))
    L.push("")
    L.push(sec("Colors:View", [contLow, surf, prim, prim, prim, onSurfVar, prim, err, onSurf, onSurf, ter]))
    L.push("")
    L.push(sec("Colors:Button", [contLow, contHigh, prim, prim, prim, onSurfVar, prim, err, onSurf, onSurf, ter]))
    L.push("")
    L.push(sec("Colors:Selection", [primCont, prim, prim, prim, onPrim, onPrimCont, onPrim, onErr, onPrim, onPrim, onPrim]))
    L.push("")
    L.push(sec("Colors:Tooltip", [invSurf, invSurf, prim, prim, invOnSurf, invOnSurf, prim, err, invOnSurf, invOnSurf, ter]))
    L.push("")
    L.push(sec("Colors:Complementary", [cont, contHigh, prim, prim, onPrim, onSurfVar, prim, err, onSurf, onSurf, ter]))
    L.push("")
    L.push("[ColorEffects:Disabled]")
    L.push("Color=56,56,56")
    L.push("ColorAmount=0")
    L.push("ColorEffect=0")
    L.push("ContrastAmount=0.65")
    L.push("ContrastEffect=1")
    L.push("IntensityAmount=-1")
    L.push("IntensityEffect=0")
    L.push("")
    L.push("[ColorEffects:Inactive]")
    L.push("ChangeSelectionColor=true")
    L.push("Color=112,111,110")
    L.push("ColorAmount=0.025")
    L.push("ColorEffect=2")
    L.push("ContrastAmount=0.1")
    L.push("ContrastEffect=2")
    L.push("Enable=true")
    L.push("IntensityAmount=0.45")
    L.push("IntensityEffect=2")
    return L.join("\n") + "\n"
  }

  function gtkCssText() {
    function D(n, v) {
      return "@define-color " + n + " " + v + ";"
    }
    var dark = DynamicTheme.darkMode
    var surf = DynamicTheme.role("surface", "#111111")
    var onSurf = DynamicTheme.role("on_surface", "#ffffff")
    var cont = DynamicTheme.role("surface_container", "#111111")
    var contHigh = DynamicTheme.role("surface_container_high", "#111111")
    var contLow = DynamicTheme.role("surface_container_low", "#111111")
    var bg = DynamicTheme.role("background", "#111111")
    var prim = DynamicTheme.role("primary", "#bbbbbb")
    var onPrim = DynamicTheme.role("on_primary", "#000000")
    var shade = dark ? "rgba(0,0,0,0.36)" : "rgba(0,0,0,0.12)"
    var L = []
    L.push("/* Generated by sharkshell app theme - do not edit. */")
    L.push(D("window_bg_color", surf))
    L.push(D("window_fg_color", onSurf))
    L.push(D("view_bg_color", surf))
    L.push(D("view_fg_color", onSurf))
    L.push(D("headerbar_bg_color", cont))
    L.push(D("headerbar_fg_color", onSurf))
    L.push(D("headerbar_border_color", cont))
    L.push(D("headerbar_backdrop_color", contLow))
    L.push(D("headerbar_shade_color", contLow))
    L.push(D("card_bg_color", cont))
    L.push(D("card_fg_color", onSurf))
    L.push(D("dialog_bg_color", surf))
    L.push(D("dialog_fg_color", onSurf))
    L.push(D("popover_bg_color", contHigh))
    L.push(D("popover_fg_color", onSurf))
    L.push(D("sidebar_bg_color", contLow))
    L.push(D("sidebar_fg_color", onSurf))
    L.push(D("sidebar_backdrop_color", contLow))
    L.push(D("sidebar_border_color", contLow))
    L.push(D("secondary_sidebar_bg_color", cont))
    L.push(D("secondary_sidebar_fg_color", onSurf))
    L.push(D("accent_bg_color", prim))
    L.push(D("accent_fg_color", onPrim))
    L.push(D("accent_color", prim))
    L.push(D("destructive_bg_color", DynamicTheme.role("error", "#ff5555")))
    L.push(D("destructive_fg_color", DynamicTheme.role("on_error", "#000000")))
    L.push(D("success_bg_color", DynamicTheme.role("tertiary", "#888888")))
    L.push(D("success_fg_color", onSurf))
    L.push(D("theme_bg_color", bg))
    L.push(D("theme_fg_color", DynamicTheme.role("on_background", "#ffffff")))
    L.push(D("theme_base_color", surf))
    L.push(D("theme_text_color", onSurf))
    L.push(D("theme_selected_bg_color", prim))
    L.push(D("theme_selected_fg_color", onPrim))
    L.push(D("shade_color", shade))
    L.push(D("scrollbar_outline_color", dark ? "rgba(255,255,255,0.10)" : "rgba(0,0,0,0.10)"))
    L.push("")
    L.push("* { border-radius: 0px; }")
    return L.join("\n") + "\n"
  }

  function qtengineJsonText() {
    var o = {
      theme: {
        colorScheme: root.kdeColorsPath,
        iconTheme: root.iconTheme(),
        style: "breeze",
        font: { family: Theme.fontFamily, size: 11, weight: -1 },
        fontFixed: { family: Theme.fontFamily, size: 11, weight: -1 }
      },
      misc: {
        singleClickActivate: false,
        menusHaveIcons: true,
        shortcutsForContextMenus: true
      }
    }
    return JSON.stringify(o)
  }

  function settingsIniText(cur, dark) {
    var d = (dark === undefined ? DynamicTheme.darkMode : !!dark)
    var darkFlag = d ? "1" : "0"
    var icon = d ? "Papirus-Dark" : "Papirus"
    var pairs = [
      ["gtk-theme-name", "Adwaita"],
      ["gtk-icon-theme-name", icon],
      ["gtk-font-name", Theme.fontFamily + " 10"],
      ["gtk-cursor-theme-name", "Adwaita"],
      ["gtk-cursor-theme-size", "24"],
      ["gtk-application-prefer-dark-theme", darkFlag]
    ]
    var t = String(cur || "")
    if (t.trim() === "") {
      var fresh = ["[Settings]"]
      for (var i = 0; i < pairs.length; i++)
        fresh.push(pairs[i][0] + "=" + pairs[i][1])
      return fresh.join("\n") + "\n"
    }
    var lines = t.split("\n")
    var seen = {}
    for (var j = 0; j < lines.length; j++) {
      var m = /^\s*([A-Za-z0-9-]+)\s*=/.exec(lines[j])
      if (!m)
        continue
      for (var k = 0; k < pairs.length; k++) {
        if (pairs[k][0] === m[1]) {
          lines[j] = m[1] + "=" + pairs[k][1]
          seen[m[1]] = true
        }
      }
    }
    for (var q = 0; q < pairs.length; q++)
      if (!seen[pairs[q][0]])
        lines.push(pairs[q][0] + "=" + pairs[q][1])
    return lines.join("\n").replace(/\n*$/, "\n")
  }

  function flatpakOverridesText(dark) {
    var d = (dark === undefined ? DynamicTheme.darkMode : !!dark)
    var L = []
    L.push("[Context]")
    L.push("filesystems=xdg-config/gtk-3.0:ro;xdg-config/gtk-4.0:ro;xdg-config/kdeglobals:ro;xdg-data/color-schemes:ro;xdg-data/themes:ro;xdg-data/icons:ro;/nix/store:ro;")
    L.push("")
    L.push("[Environment]")
    L.push("GTK_THEME=Adwaita")
    L.push("ICON_THEME=" + (d ? "Papirus-Dark" : "Papirus"))
    L.push("QT_QPA_PLATFORMTHEME=kde")
    return L.join("\n") + "\n"
  }

  function dconfPush(dark) {
    var d = (dark === undefined ? DynamicTheme.darkMode : !!dark)
    var scheme = d ? "dark" : "light"
    var icon = d ? "Papirus-Dark" : "Papirus"
    var font = Theme.fontFamily + " 10"
    dconfProc.running = false
    dconfProc.command = ["bash", "-c",
      "dconf write /org/gnome/desktop/interface/color-scheme \"'prefer-" + scheme + "'\";"
      + " dconf write /org/gnome/desktop/interface/gtk-theme \"'Adwaita'\";"
      + " dconf write /org/gnome/desktop/interface/icon-theme \"'" + icon + "'\";"
      + " dconf write /org/gnome/desktop/interface/font-name \"'" + font + "'\";"
      + " dconf write /org/gnome/desktop/interface/monospace-font-name \"'" + font + "'\""]
    dconfProc.running = true
  }

  function push() {
    if (!DynamicTheme.enabled)
      return
    kdeColorsFile.setText(root.kdeColorsText())
    qtengineFile.setText(root.qtengineJsonText())
    var css = root.gtkCssText()
    gtkCssFile3.setText(css)
    gtkCssFile4.setText(css)
    gtkIniFile3.setText(root.settingsIniText(root.iniText3))
    gtkIniFile4.setText(root.settingsIniText(root.iniText4))
    overridesFile.setText(root.flatpakOverridesText())
    root.dconfPush()
  }

  function reset() {
    resetThemeProc.running = false
    resetThemeProc.running = true
    gtkIniFile3.setText(root.settingsIniText(root.iniText3, true))
    gtkIniFile4.setText(root.settingsIniText(root.iniText4, true))
    overridesFile.setText(root.flatpakOverridesText(true))
    root.dconfPush(true)
  }

  Process {
    id: dconfProc
  }

  Process {
    id: resetThemeProc
    command: ["bash", "-c", "rm -f \"$HOME/.config/qtengine/config.json\" \"$HOME/.config/sharkshell/kde-dynamic.colors\" \"$HOME/.config/gtk-3.0/gtk.css\" \"$HOME/.config/gtk-4.0/gtk.css\""]
  }

  Process {
    id: mkdirProc
    command: ["bash", "-c", "mkdir -p \"$HOME/.config/qtengine\" \"$HOME/.local/share/flatpak/overrides\""]
  }

  FileView {
    id: kdeColorsFile
    path: root.kdeColorsPath
    watchChanges: false
    printErrors: false
  }

  FileView {
    id: qtengineFile
    path: root.qtengineConfigPath
    watchChanges: false
    printErrors: false
  }

  FileView {
    id: gtkCssFile3
    path: root.gtk3CssPath
    watchChanges: false
    printErrors: false
  }

  FileView {
    id: gtkCssFile4
    path: root.gtk4CssPath
    watchChanges: false
    printErrors: false
  }

  FileView {
    id: gtkIniFile3
    path: root.gtk3IniPath
    watchChanges: false
    printErrors: false
    onLoaded: root.iniText3 = text()
  }

  FileView {
    id: gtkIniFile4
    path: root.gtk4IniPath
    watchChanges: false
    printErrors: false
    onLoaded: root.iniText4 = text()
  }

  FileView {
    id: overridesFile
    path: root.flatpakOverridesPath
    watchChanges: false
    printErrors: false
  }

  Component.onCompleted: {
    if (!mkdirProc.running)
      mkdirProc.running = true
  }
}
