pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// Transparency mode (independent from the dynamic wallpaper theme).
//
// When on: quickshell surfaces (Theme.bg / Theme.bgAlt) turn translucent
// with niri background blur behind them, and the kitty terminal goes
// translucent (via its own config) with blur behind it too.
// Borders and text stay opaque for readability.
// When off (default): everything exactly as before.
//
// The niri side lives in ~/.config/niri-dynamic/transparency.kdl,
// included by the stock niri config. Quickshell rewrites it on toggle.
// The kitty side lives in ~/.cache/sharkshell/kitty-transparency.conf,
// included at the end of kitty.conf.
Scope {
  id: root

  property bool transparent: false

  // Terminal translucency while transparent mode is on.
  readonly property real terminalOpacity: 0.85

  readonly property string cacheDir: Quickshell.env("HOME") + "/.cache/sharkshell"
  readonly property string kittyTransName: "kitty-transparency.conf"
  readonly property string niriDir: Quickshell.env("HOME") + "/.config/niri-dynamic"
  readonly property string niriTransparency: root.niriDir + "/transparency.kdl"

  function setTransparent(v) {
    root.transparent = !!v
  }

  function toggle() {
    root.setTransparent(!root.transparent)
  }

  function shellQuote(value) {
    return "'" + String(value).replace(/'/g, "'\\''") + "'"
  }

  onTransparentChanged: {
    flagFile.setText(root.transparent ? "1" : "0")
    root.writeNiri()
    root.reloadNiri()
    root.writeKittyTrans()
    root.reloadKitty()
  }

  IpcHandler {
    target: "transparency"
    function toggle(): void { root.toggle() }
    function enable(): void { root.setTransparent(true) }
    function disable(): void { root.setTransparent(false) }
  }

  FileView {
    id: flagFile
    path: root.cacheDir + "/transparent-mode"
    watchChanges: true
    printErrors: false
    onLoaded: {
      var t = text().trim()
      if (t !== "")
        root.transparent = (t === "1")
    }
    onFileChanged: reload()
  }

  FileView {
    id: niriFile
    path: root.niriTransparency
    watchChanges: false
    printErrors: false
  }

  FileView {
    id: kittyTransFile
    path: root.cacheDir + "/" + root.kittyTransName
    watchChanges: false
    printErrors: false
  }

  function niriText() {
    if (!root.transparent)
      return "// Transparency off (default) - no extra rules.\n"
    return "// Generated by sharkshell transparency mode - do not edit.\n"
      + "window-rule {\n"
      + "  match app-id=\"^kitty$\"\n"
      + "  background-effect {\n"
      + "    blur true\n"
      + "    xray true\n"
      + "  }\n"
      + "}\n"
      + "layer-rule {\n"
      + "  match namespace=\"^quickshell$\"\n"
      + "  background-effect {\n"
      + "    blur true\n"
      + "    xray true\n"
      + "  }\n"
      + "}\n"
      + "layer-rule {\n"
      + "  match namespace=\"^quickshell-modal$\"\n"
      + "  background-effect {\n"
      + "    blur true\n"
      + "    xray true\n"
      + "  }\n"
      + "}\n"
      + "layer-rule {\n"
      + "  match namespace=\"^quickshell-blur$\"\n"
      + "  background-effect {\n"
      + "    blur true\n"
      + "    xray true\n"
      + "  }\n"
      + "}\n"
  }

  function writeNiri() {
    niriFile.setText(root.niriText())
  }

  function writeKittyTrans() {
    kittyTransFile.setText("# Generated by sharkshell transparency mode - do not edit.\n"
      + "background_opacity " + (root.transparent ? root.terminalOpacity : 1.0) + "\n")
  }

  Process {
    id: mkdirProc
    command: ["bash", "-c",
      "mkdir -p " + root.shellQuote(root.cacheDir) + " " + root.shellQuote(root.niriDir)]
    onExited: {
      root.writeNiri()
      root.writeKittyTrans()
    }
  }

  Process {
    id: niriReloadProc
    command: ["bash", "-c",
      "rt=\"$XDG_RUNTIME_DIR\"; [ -z \"$rt\" ] && rt=\"/run/user/$(id -u)\";"
      + " for s in \"$rt\"/niri.*.sock; do"
      + " [ -S \"$s\" ] || continue;"
      + " NIRI_SOCKET=\"$s\" niri msg action load-config-file >/dev/null 2>&1;"
      + " done; exit 0"]
  }

  function reloadNiri() {
    if (!niriReloadProc.running)
      niriReloadProc.running = true
    settleTimer.restart()
  }

  Process {
    id: kittyReloadProc
    command: ["pkill", "-USR1", "kitty"]
  }

  // See DynamicTheme: re-fire reloads after file writes have landed.
  Timer {
    id: settleTimer
    interval: 1500
    onTriggered: {
      if (!kittyReloadProc.running)
        kittyReloadProc.running = true
      if (!niriReloadProc.running)
        niriReloadProc.running = true
    }
  }

  function reloadKitty() {
    if (!kittyReloadProc.running)
      kittyReloadProc.running = true
    settleTimer.restart()
  }

  Component.onCompleted: {
    if (!mkdirProc.running)
      mkdirProc.running = true
  }
}
