pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import "Util.js" as Util

Scope {
  id: root

  property bool transparent: false
  property real amount: 0.15
  readonly property real amountDef: 0.15
  readonly property real amountMax: 0.5

  readonly property real terminalOpacity: 1.0 - root.amount

  readonly property string cacheDir: Quickshell.env("HOME") + "/.cache/sharkshell"
  readonly property string kittyTransName: "kitty-transparency.conf"
  readonly property string niriDir: Quickshell.env("HOME") + "/.config/sharkshell"
  readonly property string niriTransparency: root.niriDir + "/niri/transparency.kdl"
  readonly property string niriBlur: root.niriDir + "/niri/blur.kdl"

  function setTransparent(v) {
    root.transparent = !!v
  }

  function toggle() {
    root.setTransparent(!root.transparent)
  }

  function setAmount(v) {
    v = parseFloat(v)
    if (isNaN(v)) return
    root.amount = Math.min(root.amountMax, Math.max(0, v))
  }

  function resetAmount() {
    root.setAmount(root.amountDef)
  }

  onAmountChanged: {
    amountFile.setText(String(Math.round(root.amount * 100) / 100))
    root.pushKittyTrans()
    DynamicTheme.refreshFoot()
  }

  onTransparentChanged: {
    flagFile.setText(root.transparent ? "1" : "0")
    root.writeNiri()
    root.writeBlur()
    root.reloadNiri()
    root.pushKittyTrans()
    DynamicTheme.refreshFoot()
    root.reloadKitty()
  }

  IpcHandler {
    target: "transparency"
    function toggle(): void { root.toggle() }
    function enable(): void { root.setTransparent(true) }
    function disable(): void { root.setTransparent(false) }
    function setAmount(v: real): void { root.setAmount(v) }
  }

  FileView {
    id: amountFile
    path: root.cacheDir + "/transparency-level"
    watchChanges: true
    printErrors: false
    onLoaded: {
      const v = parseFloat(text().trim())
      if (!isNaN(v)) root.amount = Math.min(root.amountMax, Math.max(0, v))
    }
    onFileChanged: reload()
  }

  FileView {
    id: flagFile
    path: root.cacheDir + "/transparent-mode"
    watchChanges: true
    printErrors: false
    onLoaded: {
      var t = text().trim()
      if (t !== "")
        root.transparent = (t === "1")
    }
    onFileChanged: reload()
  }

  FileView {
    id: niriFile
    path: root.niriTransparency
    watchChanges: false
    printErrors: false
  }

  FileView {
    id: niriBlurFile
    path: root.niriBlur
    watchChanges: false
    printErrors: false
  }

  Connections {
    target: BlurState
    function onRadiusChanged() {
      root.writeBlur()
      blurTimer.restart()
    }
  }

  Timer {
    id: blurTimer
    interval: 400
    onTriggered: {
      root.writeBlur()
      root.reloadNiri()
    }
  }

  function niriText() {
    if (!root.transparent)
      return "// Transparency off (default) - no extra rules.\n"
    return "// Generated by sharkshell transparency mode - do not edit.\n"
      + "window-rule {\n"
      + "  match app-id=\"^(kitty|btop)$\"\n"
      + "  background-effect {\n"
      + "    blur true\n"
      + "    xray true\n"
      + "  }\n"
      + "}\n"
      + "window-rule {\n"
      + "  match app-id=\"^foot$\"\n"
      + "  background-effect {\n"
      + "    blur true\n"
      + "    xray true\n"
      + "  }\n"
      + "}\n"
  }

  function writeNiri() {
    niriFile.setText(root.niriText())
  }

  function writeBlur() {
    const r = BlurState.radius
    const passes = 1 + Math.round(r / 8)
    const offset = Math.round(r / 32 * 60) / 10
    let txt = "// Generated by sharkshell blur slider - do not edit.\n"
      + "blur {\n"
      + "  passes " + passes + "\n"
      + "  offset " + offset.toFixed(1) + "\n"
      + "  noise 0.03\n"
      + "  saturation 1.0\n"
      + "}\n"
    if (root.transparent)
      txt += "layer-rule {\n"
        + "  match namespace=\"^quickshell-modal$\"\n"
        + "  background-effect { blur true }\n"
        + "}\n"
    niriBlurFile.setText(txt)
  }

  function writeKittyTrans() {
    root.pushKittyTrans()
  }

  function kittyTransText() {
    const op = root.transparent ? Math.round(root.terminalOpacity * 100) / 100 : 1.0
    return "# Generated by sharkshell transparency mode - do not edit.\n"
      + "background_opacity " + op + "\n"
  }

  Process {
    id: kittyTransProc
    command: ["bash", "-c",
      "printf '%s' " + Util.shellQuote(root.kittyTransText())
      + " > " + Util.shellQuote(root.niriDir + "/kitty/" + root.kittyTransName) + ";"
      + " pkill -USR1 kitty >/dev/null 2>&1; exit 0"]
  }

  function pushKittyTrans() {
    if (!kittyTransProc.running)
      kittyTransProc.running = true
    kittyTimer.restart()
  }

  Process {
    id: mkdirProc
    command: ["bash", "-c",
      "mkdir -p " + Util.shellQuote(root.cacheDir) + " " + Util.shellQuote(root.niriDir + "/niri") + " " + Util.shellQuote(root.niriDir + "/kitty")]
    onExited: {
      root.writeNiri()
      root.writeKittyTrans()
    }
  }

  Process {
    id: niriReloadProc
    command: ["bash", "-c",
      "rt=\"$XDG_RUNTIME_DIR\"; [ -z \"$rt\" ] && rt=\"/run/user/$(id -u)\";"
      + " for s in \"$rt\"/niri.*.sock; do"
      + " [ -S \"$s\" ] || continue;"
      + " NIRI_SOCKET=\"$s\" niri msg action load-config-file >/dev/null 2>&1;"
      + " done; exit 0"]
  }

  function reloadNiri() {
    if (!niriReloadProc.running)
      niriReloadProc.running = true
    settleTimer.restart()
  }

  Process {
    id: kittyReloadProc
    command: ["pkill", "-USR1", "kitty"]
  }

  Timer {
    id: kittyTimer
    interval: 500
    onTriggered: {
      if (!kittyTransProc.running)
        kittyTransProc.running = true
      DynamicTheme.refreshFoot()
    }
  }

  Timer {
    id: settleTimer
    interval: 1500
    onTriggered: {
      if (!kittyReloadProc.running)
        kittyReloadProc.running = true
      if (!niriReloadProc.running)
        niriReloadProc.running = true
    }
  }

  function reloadKitty() {
    if (!kittyReloadProc.running)
      kittyReloadProc.running = true
    settleTimer.restart()
  }

  Component.onCompleted: {
    if (!mkdirProc.running)
      mkdirProc.running = true
  }
}
